apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
spec:
  replicas: 3
  # Match on the AlertmanagerConfig
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: alertmanagerconfig
