apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  evaluationInterval: 30s
  image: quay.io/prometheus/prometheus:v3.4.1
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  logLevel: info
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 1
  retention: 30d
  scrapeInterval: 30s
  serviceAccountName: prometheus-applications
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  serviceMonitorSelector:
    matchLabels:
      # Only match ServiceMonitors that have the monitoring: prometheus-applications label
      monitoring: prometheus-applications
  # References the `additional-scrape-configs` secret
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: additional-prometheus-job.yaml
  shards: 1
  alerting:
    alertmanagers:
      # Match on the endpoint object
      - name: alertmanager-operated
        port: web
  ruleSelector:
    matchLabels:
      role: alert-rules
  version: v3.4.1