apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    role: alert-rules
  name: prometheus-example-rules
spec:
  groups:
    - name: SimpleAlert
      rules:
        - alert: ExampleAlert
          expr: vector(1)