networks:
  prometheus:
    name: prometheus
    driver: bridge
services:
  go-application:
    build:
      context: ../go-application
    container_name: go-application
    image: go-application
    ports:
      - "80:5000"
    networks:
      - prometheus
  python-application:
    build:
      context: ../python-application
    container_name: python-application
    image: python-application
    ports:
      - "81:5000"
    networks:
      - prometheus
  dotnet-application:
    build:
      context: ../dotnet-application
    container_name: dotnet-application
    image: dotnet-application
    ports:
      - "82:5000"
    networks:
      - prometheus
  nodejs-application:
    build:
      context: ../nodejs-application
    container_name: nodejs-application
    image: nodejs-application
    ports:
      - "83:5000"
    networks:
      - prometheus
  prometheus-00:
    container_name: prometheus-00
    image: prom/prometheus:v3.3.0
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=http://prometheus-00:9090'
      - '--web.route-prefix=/'
      # Important for Thanos integration: disable internal Prometheus compaction
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'
    volumes:
      - ./prometheus-00.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - prometheus
  prometheus-01:
    container_name: prometheus-01
    image: prom/prometheus:v3.3.0
    ports:
      - "9091:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=http://prometheus-01:9090'
      - '--web.route-prefix=/'
      # Important for Thanos integration: disable internal Prometheus compaction
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'
    volumes:
      - ./prometheus-01.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - prometheus