apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.38.0
        args:
        - "query"
          # Thanos Query HTTP API, for Grafana and UI
        - "--http-address=0.0.0.0:19090"
          # Thanos Query gRPC API, for other Thanos components
        - "--grpc-address=0.0.0.0:19091"
        # Connect to Prometheus Thanos sidecars using the k8s service names over gRPC port 19091
        - --endpoint=dnssrv+_grpc._tcp.prometheus-operated.default.svc.cluster.local
        ports:
        - name: http
          containerPort: 19090
          protocol: TCP
        - name: grpc
          containerPort: 19091
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  selector:
    app: thanos-query
  ports:
  - name: http
    protocol: TCP
    port: 19090
    targetPort: http
  - name: grpc
    protocol: TCP
    port: 19091
    targetPort: grpc
  # Use ClusterIP for internal access. For external, consider NodePort or Ingress.
  type: ClusterIP